### 테스트용 docker compose 파일

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "9902:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: SilkaStory
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
